/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_final_eduardo_barahona;

import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author eduar
 */
public class Pantalla extends javax.swing.JFrame {

    public Pantalla() {
          initComponents();
          // metodo para centrar la ventana
          centrarVentana(); 
          menuGaraje.setEnabled(false);  //des el boton
          menuTuning.setEnabled(false);  //des el boton
          menuCarrera.setEnabled(false);  //des el boton
        
            // Ocultar las imagenes de los carros antes de comenzar
            CarroCarrera1.setVisible(false);
            CarroCarrera2.setVisible(false);
            CarroCarrera3.setVisible(false);

            carreraMenu.setVisible(false);
        
    }
    
    
    private void centrarVentana() {
    // Obtiene el tamaño de la pantalla
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    // Obtiene el tamaño de la ventana
    Dimension frameSize = this.getSize();
    // Calcula la posición (x, y)
    int x = (screenSize.width - frameSize.width) / 2;
    int y = (screenSize.height - frameSize.height) / 2;
    // Establece la ubicación de la ventana
    this.setLocation(x, y);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        menuCarrera = new javax.swing.JButton();
        menuTuning = new javax.swing.JButton();
        menuGaraje = new javax.swing.JButton();
        menuCerrar = new javax.swing.JButton();
        tMenuPrincipal = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        Logos = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        logoBMW = new javax.swing.JLabel();
        logoLambo = new javax.swing.JLabel();
        seleccionaMarca = new javax.swing.JLabel();
        logoFerrari = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        Lambo = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        lamboMenu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lamboHuracan = new javax.swing.JLabel();
        fondoLambo = new javax.swing.JLabel();
        Ferrari = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        FerrariMenu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ferrariLaferrari = new javax.swing.JLabel();
        fondoFerrari = new javax.swing.JLabel();
        Garaje = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        garajeMenu = new javax.swing.JButton();
        GarajeCarroNitro = new javax.swing.JLabel();
        GarajeCarroMotor = new javax.swing.JLabel();
        GarajeCarroVelocidad = new javax.swing.JLabel();
        GarajeCarroAnio = new javax.swing.JLabel();
        GarajeCarroModelo = new javax.swing.JLabel();
        GarajeCarroMarca = new javax.swing.JLabel();
        seleccionaMarca1 = new javax.swing.JLabel();
        garajeCarroImagen = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();
        Tuning = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tuningNivelVelocidad = new javax.swing.JLabel();
        tuningNivelNitro = new javax.swing.JLabel();
        tuningNivelMotor = new javax.swing.JLabel();
        tuningMejorarNitro = new javax.swing.JButton();
        tuningMejorarVelocidad = new javax.swing.JButton();
        tuningMejorarMotor = new javax.swing.JButton();
        tunningMenu = new javax.swing.JButton();
        seleccionaMarca2 = new javax.swing.JLabel();
        Fondo3 = new javax.swing.JLabel();
        Carrera = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        CarroCarrera3 = new javax.swing.JLabel();
        CarroCarrera2 = new javax.swing.JLabel();
        CarroCarrera1 = new javax.swing.JLabel();
        carreraMenu = new javax.swing.JButton();
        empezarCarrera = new javax.swing.JButton();
        seleccionaMarca3 = new javax.swing.JLabel();
        Fondo4 = new javax.swing.JLabel();
        BMW = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        BmwMenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bmwM4 = new javax.swing.JLabel();
        fondoFerrari1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonInicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        Menu.setUndecorated(true);
        Menu.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuCarrera.setBackground(new java.awt.Color(0, 0, 0));
        menuCarrera.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        menuCarrera.setForeground(new java.awt.Color(255, 255, 255));
        menuCarrera.setText("Carrera");
        menuCarrera.setActionCommand("Tunner");
        menuCarrera.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        menuCarrera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCarreraActionPerformed(evt);
            }
        });
        jPanel3.add(menuCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 150, 40));

        menuTuning.setBackground(new java.awt.Color(0, 0, 0));
        menuTuning.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        menuTuning.setForeground(new java.awt.Color(255, 255, 255));
        menuTuning.setText("Mejorar Vehiculo");
        menuTuning.setActionCommand("Tunner");
        menuTuning.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        menuTuning.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuTuning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTuningActionPerformed(evt);
            }
        });
        jPanel3.add(menuTuning, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 150, 40));

        menuGaraje.setBackground(new java.awt.Color(0, 0, 0));
        menuGaraje.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        menuGaraje.setForeground(new java.awt.Color(255, 255, 255));
        menuGaraje.setText("Mi Garaje");
        menuGaraje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        menuGaraje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuGaraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGarajeActionPerformed(evt);
            }
        });
        jPanel3.add(menuGaraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 150, 40));

        menuCerrar.setBackground(new java.awt.Color(255, 51, 51));
        menuCerrar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        menuCerrar.setForeground(new java.awt.Color(255, 255, 255));
        menuCerrar.setText("Cerrar");
        menuCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        menuCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarActionPerformed(evt);
            }
        });
        jPanel3.add(menuCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 150, 40));

        tMenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        tMenuPrincipal.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        tMenuPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        tMenuPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tMenuPrincipal.setText("exo racing - menu");
        tMenuPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        tMenuPrincipal.setOpaque(true);
        jPanel3.add(tMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/menu.jpg"))); // NOI18N
        Fondo1.setText("jLabel4");
        jPanel3.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 960, 560));

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu.getContentPane());
        Menu.getContentPane().setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Logos.setUndecorated(true);
        Logos.setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoBMW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/BMW-logo.png"))); // NOI18N
        logoBMW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoBMW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoBMWMouseClicked(evt);
            }
        });
        jPanel2.add(logoBMW, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 130, -1));

        logoLambo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/Lamborghini-Logo.png"))); // NOI18N
        logoLambo.setText("jLabel6");
        logoLambo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoLambo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoLamboMouseClicked(evt);
            }
        });
        jPanel2.add(logoLambo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 150, 140));

        seleccionaMarca.setBackground(new java.awt.Color(255, 255, 255));
        seleccionaMarca.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        seleccionaMarca.setForeground(new java.awt.Color(0, 0, 0));
        seleccionaMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleccionaMarca.setText("SELECCIONA tu vehiculo");
        seleccionaMarca.setOpaque(true);
        jPanel2.add(seleccionaMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 940, 40));

        logoFerrari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/ferrari-logo.png"))); // NOI18N
        logoFerrari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoFerrari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoFerrariMouseClicked(evt);
            }
        });
        jPanel2.add(logoFerrari, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 100, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/fondo.jpg"))); // NOI18N
        Fondo.setText("jLabel4");
        jPanel2.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        javax.swing.GroupLayout LogosLayout = new javax.swing.GroupLayout(Logos.getContentPane());
        Logos.getContentPane().setLayout(LogosLayout);
        LogosLayout.setHorizontalGroup(
            LogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        LogosLayout.setVerticalGroup(
            LogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Lambo.setUndecorated(true);
        Lambo.setResizable(false);
        Lambo.setSize(new java.awt.Dimension(960, 530));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lamboMenu.setText("MENU");
        lamboMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamboMenuActionPerformed(evt);
            }
        });
        jPanel4.add(lamboMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 90, 30));

        jLabel7.setBackground(new java.awt.Color(204, 102, 0));
        jLabel7.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LAMBORGHINI");
        jLabel7.setOpaque(true);
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 920, 40));

        lamboHuracan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/lambo2.png"))); // NOI18N
        lamboHuracan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lamboHuracanMouseClicked(evt);
            }
        });
        jPanel4.add(lamboHuracan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        fondoLambo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/taller.jpg"))); // NOI18N
        jPanel4.add(fondoLambo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        javax.swing.GroupLayout LamboLayout = new javax.swing.GroupLayout(Lambo.getContentPane());
        Lambo.getContentPane().setLayout(LamboLayout);
        LamboLayout.setHorizontalGroup(
            LamboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LamboLayout.setVerticalGroup(
            LamboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Ferrari.setUndecorated(true);
        Ferrari.setResizable(false);
        Ferrari.setSize(new java.awt.Dimension(960, 530));

        jPanel5.setPreferredSize(new java.awt.Dimension(960, 530));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FerrariMenu.setBackground(new java.awt.Color(0, 0, 0));
        FerrariMenu.setForeground(new java.awt.Color(255, 255, 255));
        FerrariMenu.setText("MENU");
        FerrariMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FerrariMenuActionPerformed(evt);
            }
        });
        jPanel5.add(FerrariMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FERRARI");
        jLabel4.setOpaque(true);
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 920, 40));

        ferrariLaferrari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/Ferrari2.png"))); // NOI18N
        ferrariLaferrari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ferrariLaferrariMouseClicked(evt);
            }
        });
        jPanel5.add(ferrariLaferrari, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        fondoFerrari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/taller.jpg"))); // NOI18N
        jPanel5.add(fondoFerrari, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        javax.swing.GroupLayout FerrariLayout = new javax.swing.GroupLayout(Ferrari.getContentPane());
        Ferrari.getContentPane().setLayout(FerrariLayout);
        FerrariLayout.setHorizontalGroup(
            FerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FerrariLayout.setVerticalGroup(
            FerrariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Garaje.setUndecorated(true);
        Garaje.setResizable(false);

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        garajeMenu.setBackground(new java.awt.Color(255, 255, 255));
        garajeMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        garajeMenu.setForeground(new java.awt.Color(0, 0, 0));
        garajeMenu.setText("MENU");
        garajeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garajeMenuActionPerformed(evt);
            }
        });
        jPanel7.add(garajeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 200, -1));

        GarajeCarroNitro.setBackground(new java.awt.Color(0, 0, 0));
        GarajeCarroNitro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        GarajeCarroNitro.setForeground(new java.awt.Color(255, 255, 255));
        GarajeCarroNitro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GarajeCarroNitro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        GarajeCarroNitro.setOpaque(true);
        jPanel7.add(GarajeCarroNitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 190, 40));

        GarajeCarroMotor.setBackground(new java.awt.Color(0, 0, 0));
        GarajeCarroMotor.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        GarajeCarroMotor.setForeground(new java.awt.Color(255, 255, 255));
        GarajeCarroMotor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GarajeCarroMotor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        GarajeCarroMotor.setOpaque(true);
        jPanel7.add(GarajeCarroMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 190, 40));

        GarajeCarroVelocidad.setBackground(new java.awt.Color(0, 0, 0));
        GarajeCarroVelocidad.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        GarajeCarroVelocidad.setForeground(new java.awt.Color(255, 255, 255));
        GarajeCarroVelocidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GarajeCarroVelocidad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        GarajeCarroVelocidad.setOpaque(true);
        jPanel7.add(GarajeCarroVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 190, 40));

        GarajeCarroAnio.setBackground(new java.awt.Color(0, 0, 0));
        GarajeCarroAnio.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        GarajeCarroAnio.setForeground(new java.awt.Color(255, 255, 255));
        GarajeCarroAnio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GarajeCarroAnio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        GarajeCarroAnio.setOpaque(true);
        jPanel7.add(GarajeCarroAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 210, 40));

        GarajeCarroModelo.setBackground(new java.awt.Color(0, 0, 0));
        GarajeCarroModelo.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        GarajeCarroModelo.setForeground(new java.awt.Color(255, 255, 255));
        GarajeCarroModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GarajeCarroModelo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        GarajeCarroModelo.setOpaque(true);
        jPanel7.add(GarajeCarroModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 180, 40));

        GarajeCarroMarca.setBackground(new java.awt.Color(0, 0, 0));
        GarajeCarroMarca.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        GarajeCarroMarca.setForeground(new java.awt.Color(255, 255, 255));
        GarajeCarroMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GarajeCarroMarca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        GarajeCarroMarca.setOpaque(true);
        jPanel7.add(GarajeCarroMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 190, 40));

        seleccionaMarca1.setBackground(new java.awt.Color(255, 255, 255));
        seleccionaMarca1.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        seleccionaMarca1.setForeground(new java.awt.Color(0, 0, 0));
        seleccionaMarca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleccionaMarca1.setText("Mi garaje");
        seleccionaMarca1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        seleccionaMarca1.setOpaque(true);
        jPanel7.add(seleccionaMarca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 900, 50));

        garajeCarroImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/carro-silueta.png"))); // NOI18N
        jPanel7.add(garajeCarroImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, 180));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/taller.jpg"))); // NOI18N
        Fondo2.setText("jLabel4");
        jPanel7.add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        javax.swing.GroupLayout GarajeLayout = new javax.swing.GroupLayout(Garaje.getContentPane());
        Garaje.getContentPane().setLayout(GarajeLayout);
        GarajeLayout.setHorizontalGroup(
            GarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        GarajeLayout.setVerticalGroup(
            GarajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Tuning.setTitle("Tuning");
        Tuning.setUndecorated(true);
        Tuning.setResizable(false);

        jPanel8.setBackground(new java.awt.Color(102, 153, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/nitro.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jLabel9.setOpaque(true);
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 190, 190));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/velocimetro.png"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jLabel8.setOpaque(true);
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 190, 190));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/motor.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jLabel6.setOpaque(true);
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 190, 190));

        tuningNivelVelocidad.setBackground(new java.awt.Color(0, 0, 0));
        tuningNivelVelocidad.setForeground(new java.awt.Color(255, 255, 255));
        tuningNivelVelocidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tuningNivelVelocidad.setText("NIVEL VELOCIDAD");
        tuningNivelVelocidad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        tuningNivelVelocidad.setOpaque(true);
        jPanel8.add(tuningNivelVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 190, 30));

        tuningNivelNitro.setBackground(new java.awt.Color(0, 0, 0));
        tuningNivelNitro.setForeground(new java.awt.Color(255, 255, 255));
        tuningNivelNitro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tuningNivelNitro.setText("NIVEL NITRO");
        tuningNivelNitro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        tuningNivelNitro.setOpaque(true);
        jPanel8.add(tuningNivelNitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 190, 30));

        tuningNivelMotor.setBackground(new java.awt.Color(0, 0, 0));
        tuningNivelMotor.setForeground(new java.awt.Color(255, 255, 255));
        tuningNivelMotor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tuningNivelMotor.setText("NIVEL MOTOR");
        tuningNivelMotor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        tuningNivelMotor.setOpaque(true);
        jPanel8.add(tuningNivelMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 190, 30));

        tuningMejorarNitro.setBackground(new java.awt.Color(0, 0, 0));
        tuningMejorarNitro.setForeground(new java.awt.Color(255, 255, 255));
        tuningMejorarNitro.setText("Mejorar Nitroso");
        tuningMejorarNitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuningMejorarNitroActionPerformed(evt);
            }
        });
        jPanel8.add(tuningMejorarNitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 190, -1));

        tuningMejorarVelocidad.setBackground(new java.awt.Color(0, 0, 0));
        tuningMejorarVelocidad.setForeground(new java.awt.Color(255, 255, 255));
        tuningMejorarVelocidad.setText("Mejorar Velocidad Punta");
        tuningMejorarVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuningMejorarVelocidadActionPerformed(evt);
            }
        });
        jPanel8.add(tuningMejorarVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 190, -1));

        tuningMejorarMotor.setBackground(new java.awt.Color(0, 0, 0));
        tuningMejorarMotor.setForeground(new java.awt.Color(255, 255, 255));
        tuningMejorarMotor.setText("Mejorar Motor");
        tuningMejorarMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuningMejorarMotorActionPerformed(evt);
            }
        });
        jPanel8.add(tuningMejorarMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 190, -1));

        tunningMenu.setBackground(new java.awt.Color(255, 255, 255));
        tunningMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tunningMenu.setForeground(new java.awt.Color(0, 0, 0));
        tunningMenu.setText("MENU");
        tunningMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunningMenuActionPerformed(evt);
            }
        });
        jPanel8.add(tunningMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 200, -1));

        seleccionaMarca2.setBackground(new java.awt.Color(255, 255, 255));
        seleccionaMarca2.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        seleccionaMarca2.setForeground(new java.awt.Color(0, 0, 0));
        seleccionaMarca2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleccionaMarca2.setText("tunning menu");
        seleccionaMarca2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        seleccionaMarca2.setOpaque(true);
        jPanel8.add(seleccionaMarca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 900, 50));

        Fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/taller.jpg"))); // NOI18N
        Fondo3.setText("jLabel4");
        jPanel8.add(Fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        javax.swing.GroupLayout TuningLayout = new javax.swing.GroupLayout(Tuning.getContentPane());
        Tuning.getContentPane().setLayout(TuningLayout);
        TuningLayout.setHorizontalGroup(
            TuningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        TuningLayout.setVerticalGroup(
            TuningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Carrera.setUndecorated(true);
        Carrera.setResizable(false);

        jPanel9.setBackground(new java.awt.Color(102, 153, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CarroCarrera3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarroCarrera3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/Ferrari2.png"))); // NOI18N
        jPanel9.add(CarroCarrera3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 380, 200));

        CarroCarrera2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarroCarrera2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/lambo2.png"))); // NOI18N
        jPanel9.add(CarroCarrera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 380, 200));

        CarroCarrera1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarroCarrera1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/BMW.png"))); // NOI18N
        jPanel9.add(CarroCarrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 380, 200));

        carreraMenu.setBackground(new java.awt.Color(255, 255, 255));
        carreraMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        carreraMenu.setForeground(new java.awt.Color(0, 0, 0));
        carreraMenu.setText("MENU");
        carreraMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carreraMenuActionPerformed(evt);
            }
        });
        jPanel9.add(carreraMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 200, -1));

        empezarCarrera.setBackground(new java.awt.Color(255, 255, 255));
        empezarCarrera.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empezarCarrera.setForeground(new java.awt.Color(0, 0, 0));
        empezarCarrera.setText("CORRER!");
        empezarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarCarreraActionPerformed(evt);
            }
        });
        jPanel9.add(empezarCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 140, -1));

        seleccionaMarca3.setBackground(new java.awt.Color(255, 255, 255));
        seleccionaMarca3.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        seleccionaMarca3.setForeground(new java.awt.Color(0, 0, 0));
        seleccionaMarca3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleccionaMarca3.setText("carrera");
        seleccionaMarca3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        seleccionaMarca3.setOpaque(true);
        jPanel9.add(seleccionaMarca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 900, 50));

        Fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/circuito.jpg"))); // NOI18N
        Fondo4.setText("jLabel4");
        Fondo4.setToolTipText("");
        jPanel9.add(Fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        javax.swing.GroupLayout CarreraLayout = new javax.swing.GroupLayout(Carrera.getContentPane());
        Carrera.getContentPane().setLayout(CarreraLayout);
        CarreraLayout.setHorizontalGroup(
            CarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        CarreraLayout.setVerticalGroup(
            CarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        BMW.setUndecorated(true);
        BMW.setResizable(false);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BmwMenu.setBackground(new java.awt.Color(0, 0, 0));
        BmwMenu.setForeground(new java.awt.Color(255, 255, 255));
        BmwMenu.setText("MENU");
        BmwMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmwMenuActionPerformed(evt);
            }
        });
        jPanel6.add(BmwMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 51, 204));
        jLabel5.setFont(new java.awt.Font("ROG Fonts", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BMW");
        jLabel5.setOpaque(true);
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 920, 40));

        bmwM4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/BMW.png"))); // NOI18N
        bmwM4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmwM4MouseClicked(evt);
            }
        });
        jPanel6.add(bmwM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        fondoFerrari1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/taller.jpg"))); // NOI18N
        jPanel6.add(fondoFerrari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        javax.swing.GroupLayout BMWLayout = new javax.swing.GroupLayout(BMW.getContentPane());
        BMW.getContentPane().setLayout(BMWLayout);
        BMWLayout.setHorizontalGroup(
            BMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BMWLayout.setVerticalGroup(
            BMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(122, 131, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonInicio.setBackground(new java.awt.Color(255, 255, 255));
        botonInicio.setFont(new java.awt.Font("ROG Fonts", 0, 18)); // NOI18N
        botonInicio.setForeground(new java.awt.Color(0, 0, 0));
        botonInicio.setText("Entrar");
        botonInicio.setToolTipText("");
        botonInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        botonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });
        jPanel1.add(botonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 120, 40));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("ROG Fonts", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EXO CARS");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 940, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_eduardo_barahona/inicio.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        // TODO add your handling code here:
         Logos.setVisible(true);
         Logos.setLocation( this.getX(), this.getY());
         Logos.setSize(960, 530);
    }//GEN-LAST:event_botonInicioActionPerformed

    private void logoLamboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoLamboMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Lambo.setVisible(true);
        Lambo.setLocation( this.getX(), this.getY());
        Lambo.setSize(960, 530);
    }//GEN-LAST:event_logoLamboMouseClicked

    private void logoFerrariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoFerrariMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        Ferrari.setVisible(true);
        Ferrari.setLocation( this.getX(), this.getY());
        Ferrari.setSize(960, 530);    
    }//GEN-LAST:event_logoFerrariMouseClicked

    

    
    // CARROS
    private void ferrariLaferrariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ferrariLaferrariMouseClicked
        // TODO add your handling code here:  
              
        Garaje garaje = new Garaje(); // Crear instancia del garaje
        
        if (tieneCarro){
            
             JOptionPane.showConfirmDialog(null, "Ya tiene un carro", "Comprar Carro", JOptionPane.YES_OPTION);   
        }
       else{ 
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Deseas comprar el Ferrari LaFerrari?", "Comprar Carro", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            tieneCarro = true;

           menuGaraje.setEnabled(true);  //habilitar el boton
           menuTuning.setEnabled(true);  //habilitar el boton
           menuCarrera.setEnabled(true);  //habilitar el boton
            
             // Asignar el carro seleccionado
            carroSeleccionado = garaje.obtenerCarro("Ferrari LaFerrari");
            
            GarajeCarroMarca.setText("Marca: " + carroSeleccionado.getMarca());
            GarajeCarroModelo.setText("Modelo: " + carroSeleccionado.getModelo());
            GarajeCarroAnio.setText("Año: " + carroSeleccionado.getAño());
            
            GarajeCarroVelocidad.setText("Velocidad Maxima: " + carroSeleccionado.getVelocidadMaxima());
            GarajeCarroMotor.setText("Nivel Motor: " + carroSeleccionado.getNivelMotor());
            GarajeCarroNitro.setText("Nivel Nitro: " + carroSeleccionado.getNivelNitro()); 
            
             // Mostrar información del carro
            actualizarInformacionCarro();

            this.setVisible(false);
            Menu.setVisible(true);
            Menu.setLocation( this.getX(), this.getY());
            Menu.setSize(960, 530);
               
        }         
        }
    }//GEN-LAST:event_ferrariLaferrariMouseClicked

    
    
    
    
    private void FerrariMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FerrariMenuActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
         Logos.setVisible(true);
         Logos.setLocation( this.getX(), this.getY());
         Logos.setSize(960, 530);
    }//GEN-LAST:event_FerrariMenuActionPerformed

    private void menuGarajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGarajeActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
          Garaje.setVisible(true);
          Garaje.setLocation( this.getX(), this.getY());
          Garaje.setSize(960, 530);
         
    }//GEN-LAST:event_menuGarajeActionPerformed

    private void menuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarActionPerformed
        // TODO add your handling code here:
      System.exit(0); // Cierra la aplicación
    }//GEN-LAST:event_menuCerrarActionPerformed


    private void lamboHuracanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lamboHuracanMouseClicked
        // TODO add your handling code here:   
         Garaje garaje = new Garaje(); // Crear instancia del garaje
        
        if (tieneCarro){
            
             JOptionPane.showConfirmDialog(null, "Ya tiene un carro", "Comprar Carro", JOptionPane.YES_OPTION);   
        }
       else{ 
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Deseas comprar el Lamborghini Huracan?", "Comprar Carro", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            tieneCarro = true;

           menuGaraje.setEnabled(true);  //habilitar el boton
           menuTuning.setEnabled(true);  //habilitar el boton
           menuCarrera.setEnabled(true);  //habilitar el boton
            
             // Asignar el carro seleccionado
            carroSeleccionado = garaje.obtenerCarro("Lamborghini Huracan");
            
            GarajeCarroMarca.setText("Marca: " + carroSeleccionado.getMarca());
            GarajeCarroModelo.setText("Modelo: " + carroSeleccionado.getModelo());
            GarajeCarroAnio.setText("Año: " + carroSeleccionado.getAño());
            
            GarajeCarroVelocidad.setText("Velocidad Maxima: " + carroSeleccionado.getVelocidadMaxima());
            GarajeCarroMotor.setText("Nivel Motor: " + carroSeleccionado.getNivelMotor());
            GarajeCarroNitro.setText("Nivel Nitro: " + carroSeleccionado.getNivelNitro()); 
            
             // Mostrar información del carro
            actualizarInformacionCarro();
            
            this.setVisible(false);
            Menu.setVisible(true);
            Menu.setLocation( this.getX(), this.getY());
            Menu.setSize(960, 530);
                
        }  
        }
    }//GEN-LAST:event_lamboHuracanMouseClicked

    private void lamboMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamboMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         Logos.setVisible(true);
         Logos.setLocation( this.getX(), this.getY());
         Logos.setSize(960, 530);
    }//GEN-LAST:event_lamboMenuActionPerformed

    private void menuTuningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTuningActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         Tuning.setVisible(true);
         Tuning.setLocation( this.getX(), this.getY());
         Tuning.setSize(960, 530);
    }//GEN-LAST:event_menuTuningActionPerformed

    private void garajeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garajeMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
       Menu.setVisible(true);
         Menu.setLocation( this.getX(), this.getY());
         Menu.setSize(960, 530);
    }//GEN-LAST:event_garajeMenuActionPerformed

    private void menuCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCarreraActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        Carrera.setVisible(true);
         Carrera.setLocation( this.getX(), this.getY());
         Carrera.setSize(960, 530);
        
    }//GEN-LAST:event_menuCarreraActionPerformed

    private void tunningMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunningMenuActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        Menu.setVisible(true);
         Menu.setLocation( this.getX(), this.getY());
         Menu.setSize(960, 530);
    }//GEN-LAST:event_tunningMenuActionPerformed

    private void carreraMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carreraMenuActionPerformed
        // TODO add your handling code here:
            this.setVisible(false);
            Menu.setVisible(true);
            Menu.setLocation( this.getX(), this.getY());
            Menu.setSize(960, 530);
         
            carreraMenu.setVisible(false);
            empezarCarrera.setVisible(true);
            
            
            // Ocultar las imágenes de los carros antes de comenzar
            CarroCarrera1.setVisible(false);
            CarroCarrera2.setVisible(false);
            CarroCarrera3.setVisible(false);
         
         
    }//GEN-LAST:event_carreraMenuActionPerformed

    private void empezarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarCarreraActionPerformed
        // TODO add your handling code here:
        
             Garaje garaje = new Garaje();
             Carrera carrera = new Carrera(garaje, CarroCarrera1, CarroCarrera2, CarroCarrera3);
    
            // Iniciar la carrera
            carrera.empezar();
    
            empezarCarrera.setVisible(false);  //des el boton
            carreraMenu.setVisible(true);
    }//GEN-LAST:event_empezarCarreraActionPerformed

    
    
    
    
    private void tuningMejorarMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuningMejorarMotorActionPerformed
        // TODO add your handling code here:
        if (carroSeleccionado != null) {
        int incremento = 50;
        carroSeleccionado.setNivelMotor(carroSeleccionado.getNivelMotor() + incremento);

       
        JOptionPane.showMessageDialog(this, "¡Nivel del motor mejorado a " + carroSeleccionado.getNivelMotor() + "!", 
                                      "Mejorar Motor", JOptionPane.INFORMATION_MESSAGE);
        
         // actualiza informacion en la interfaz
        actualizarInformacionCarro();
    } else {
        JOptionPane.showMessageDialog(this, "No hay un carro seleccionado.", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
          
    }//GEN-LAST:event_tuningMejorarMotorActionPerformed

    private void tuningMejorarVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuningMejorarVelocidadActionPerformed
        // TODO add your handling code here:
        if (carroSeleccionado != null) {
        int incremento = 20; // Incremento para la velocidad máxima
        carroSeleccionado.setVelocidadMaxima(carroSeleccionado.getVelocidadMaxima() + incremento);

        // Mostrar mensaje en un cuadro de diálogo
        JOptionPane.showMessageDialog(this, "¡Velocidad máxima mejorada a " + carroSeleccionado.getVelocidadMaxima() + " km/h!", 
                                      "Mejorar Velocidad", JOptionPane.INFORMATION_MESSAGE);
         // Actualizar información en la interfaz
        actualizarInformacionCarro();
        
    } else {
        JOptionPane.showMessageDialog(this, "No hay un carro seleccionado.", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_tuningMejorarVelocidadActionPerformed

    private void tuningMejorarNitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuningMejorarNitroActionPerformed
        // TODO add your handling code here:
         if (carroSeleccionado != null) {
        int incremento = 2; // Incremento para el nitro
        carroSeleccionado.setNivelNitro(carroSeleccionado.getNivelNitro() + incremento);

        // Mostrar mensaje en un cuadro de diálogo
        JOptionPane.showMessageDialog(this, "¡Nivel de nitro mejorado a " + carroSeleccionado.getNivelNitro() + "!", 
                                      "Mejorar Nitro", JOptionPane.INFORMATION_MESSAGE);
        
         // Actualizar información en la interfaz
        actualizarInformacionCarro();
    } else {
        JOptionPane.showMessageDialog(this, "No hay un carro seleccionado.", 
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_tuningMejorarNitroActionPerformed

    private void BmwMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmwMenuActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        Logos.setVisible(true);
         Logos.setLocation( this.getX(), this.getY());
         Logos.setSize(960, 530);
    }//GEN-LAST:event_BmwMenuActionPerformed

    private void bmwM4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmwM4MouseClicked
        // TODO add your handling code here:
        Garaje garaje = new Garaje(); // Crear instancia del garaje
        
        if (tieneCarro){
            
             JOptionPane.showConfirmDialog(null, "Ya tiene un carro", "Comprar Carro", JOptionPane.YES_OPTION);   
        }
       else{ 
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Deseas comprar el BMW M4?", "Comprar Carro", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            tieneCarro = true;

           menuGaraje.setEnabled(true);  //habilitar el boton
           menuTuning.setEnabled(true);  //habilitar el boton
           menuCarrera.setEnabled(true);  //habilitar el boton
            
             // Asignar el carro seleccionado
            carroSeleccionado = garaje.obtenerCarro("BMW M4");
            
            GarajeCarroMarca.setText("Marca: " + carroSeleccionado.getMarca());
            GarajeCarroModelo.setText("Modelo: " + carroSeleccionado.getModelo());
            GarajeCarroAnio.setText("Año: " + carroSeleccionado.getAño());
            
            GarajeCarroVelocidad.setText("Velocidad Maxima: " + carroSeleccionado.getVelocidadMaxima());
            GarajeCarroMotor.setText("Nivel Motor: " + carroSeleccionado.getNivelMotor());
            GarajeCarroNitro.setText("Nivel Nitro: " + carroSeleccionado.getNivelNitro()); 
            
             // Mostrar información del carro
            actualizarInformacionCarro();
            
            this.setVisible(false);
            Menu.setVisible(true);
            Menu.setLocation( this.getX(), this.getY());
            Menu.setSize(960, 530); 
        }          
        }  
    }//GEN-LAST:event_bmwM4MouseClicked

    private void logoBMWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoBMWMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        BMW.setVisible(true);
        BMW.setLocation( this.getX(), this.getY());
        BMW.setSize(960, 530);
    }//GEN-LAST:event_logoBMWMouseClicked

   
    
    
    
    
    
    
    //ACTUALIZAR INFORMACION DEL CARRO AL MEJORARLO
    private void actualizarInformacionCarro() {
    if (carroSeleccionado != null) {
        GarajeCarroMarca.setText("Marca: " + carroSeleccionado.getMarca());
        GarajeCarroModelo.setText("Modelo: " + carroSeleccionado.getModelo());
        GarajeCarroAnio.setText("Año: " + carroSeleccionado.getAño());
        GarajeCarroVelocidad.setText("Velocidad Máxima: " + carroSeleccionado.getVelocidadMaxima());
        GarajeCarroMotor.setText("Nivel Motor: " + carroSeleccionado.getNivelMotor());
        GarajeCarroNitro.setText("Nivel Nitro: " + carroSeleccionado.getNivelNitro());
        
         tuningNivelVelocidad.setText("Velocidad Maxima: " + carroSeleccionado.getVelocidadMaxima());
            tuningNivelMotor.setText("Nivel Motor: " + carroSeleccionado.getNivelMotor());
            tuningNivelNitro.setText("Nivel Nitro: " + carroSeleccionado.getNivelNitro());
    }
}
    
  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }
 static boolean tieneCarro = false;
    static String Carro =  " " ;
    private Carro carroSeleccionado;
    private Garaje garaje; // Instancia global de Garaje

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog BMW;
    private javax.swing.JButton BmwMenu;
    private javax.swing.JDialog Carrera;
    private javax.swing.JLabel CarroCarrera1;
    private javax.swing.JLabel CarroCarrera2;
    private javax.swing.JLabel CarroCarrera3;
    private javax.swing.JDialog Ferrari;
    private javax.swing.JButton FerrariMenu;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JLabel Fondo3;
    private javax.swing.JLabel Fondo4;
    private javax.swing.JDialog Garaje;
    private javax.swing.JLabel GarajeCarroAnio;
    private javax.swing.JLabel GarajeCarroMarca;
    private javax.swing.JLabel GarajeCarroModelo;
    private javax.swing.JLabel GarajeCarroMotor;
    private javax.swing.JLabel GarajeCarroNitro;
    private javax.swing.JLabel GarajeCarroVelocidad;
    private javax.swing.JDialog Lambo;
    private javax.swing.JDialog Logos;
    private javax.swing.JDialog Menu;
    private javax.swing.JDialog Tuning;
    private javax.swing.JLabel bmwM4;
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton carreraMenu;
    private javax.swing.JButton empezarCarrera;
    private javax.swing.JLabel ferrariLaferrari;
    private javax.swing.JLabel fondoFerrari;
    private javax.swing.JLabel fondoFerrari1;
    private javax.swing.JLabel fondoLambo;
    private javax.swing.JLabel garajeCarroImagen;
    private javax.swing.JButton garajeMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lamboHuracan;
    private javax.swing.JButton lamboMenu;
    private javax.swing.JLabel logoBMW;
    private javax.swing.JLabel logoFerrari;
    private javax.swing.JLabel logoLambo;
    private javax.swing.JButton menuCarrera;
    private javax.swing.JButton menuCerrar;
    private javax.swing.JButton menuGaraje;
    private javax.swing.JButton menuTuning;
    private javax.swing.JLabel seleccionaMarca;
    private javax.swing.JLabel seleccionaMarca1;
    private javax.swing.JLabel seleccionaMarca2;
    private javax.swing.JLabel seleccionaMarca3;
    private javax.swing.JLabel tMenuPrincipal;
    private javax.swing.JButton tuningMejorarMotor;
    private javax.swing.JButton tuningMejorarNitro;
    private javax.swing.JButton tuningMejorarVelocidad;
    private javax.swing.JLabel tuningNivelMotor;
    private javax.swing.JLabel tuningNivelNitro;
    private javax.swing.JLabel tuningNivelVelocidad;
    private javax.swing.JButton tunningMenu;
    // End of variables declaration//GEN-END:variables

}
